### ISSUE TITLE
ImportError: No module name '__about__'

### ISSUE THREAD

**Issue by tmhererwa** [mardix/Propel#2]
Trying to install propel in python3 by running "pip3 install propel" but failing with error below:

Collecting propel
  Downloading Propel-0.60.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-7oop2hok/propel/setup.py", line 29, in <module>
        from propel.__about__ import *
      File "/tmp/pip-build-7oop2hok/propel/propel/__init__.py", line 31, in <module>
        from __about__ import *
    ImportError: No module named '__about__'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-7oop2hok/propel/
Please assist

**Comment by Lucky94** [comment]
Try doing by sudo, it will solve the issue.

**Comment by hjelev** [comment]
I have the same issue even when running with sudo.

**Comment by bluenetinc** [comment]
+1

**Comment by bluenetinc** [comment]
So I had to modify setup.py:
```
from propel import __about__
setup(
    name=__about__.__title__,
    version=__about__.__version__,
    license=__about__.__license__,
    author=__about__.__author__,
    author_email=__about__.__email__,
    description=__about__.__summary__,
    long_description=__about__.__doc__,
    url=__about__.__uri__,
```
Modify __init__.py"
```
from .__about__ import __version__, __title__

[line 795] parser = argparse.ArgumentParser(description="%s %s" % (__title__, __version__))
```

and then I could run it... sort of
